name: Update GitHub Profile README

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Latest Repo
        id: fetch_repo
        run: |
          LATEST_REPO=$(curl -s "https://api.github.com/users/SkyNetCloud/repos?sort=updated&per_page=1" | jq -r '.[0].name')
          LATEST_REPO_URL="https://github.com/SkyNetCloud/$LATEST_REPO"
          echo "LATEST_REPO=$LATEST_REPO" >> $GITHUB_ENV
          echo "LATEST_REPO_URL=$LATEST_REPO_URL" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s|\[.*\](https://github.com/SkyNetCloud/.*)|[$LATEST_REPO]($LATEST_REPO_URL)|" README.md

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://SkyNetCloud:${GITHUB_TOKEN}@github.com/SkyNetCloud/SkyNetCloud.git
          git add README.md
          git commit -m "Updated current project to $LATEST_REPO" || exit 0
          git push origin main
