name: Update GitHub Profile README

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Latest Repo Info
        id: fetch_repo
        run: |
          REPOS=$(curl -s "https://api.github.com/users/SkyNetCloud/repos?sort=pushed&per_page=100")

          echo "GitHub API Response:"
          echo "$REPOS"

          # Check if the response is valid JSON and an array
          if echo "$REPOS" | jq -e 'type != "array"' > /dev/null; then
            echo "❌ Error: GitHub API did not return a valid array of repos."
            exit 1
          fi

          # Filter out the repo with the same name as the username
          FILTERED=$(echo "$REPOS" | jq 'map(select(.name != "SkyNetCloud"))')

          # Safely extract the latest repo name and privacy status
          LATEST_REPO=$(echo "$FILTERED" | jq -r '.[0].name')
          IS_PRIVATE=$(echo "$FILTERED" | jq -r '.[0].private')

          # Fallback in case of null
          if [ "$LATEST_REPO" = "null" ] || [ -z "$LATEST_REPO" ]; then
            echo "❌ Error: No latest repository found."
            exit 1
          fi

          echo "LATEST_REPO=$LATEST_REPO" >> $GITHUB_ENV
          echo "IS_PRIVATE=$IS_PRIVATE" >> $GITHUB_ENV
          echo "LATEST_REPO_URL=https://github.com/SkyNetCloud/$LATEST_REPO" >> $GITHUB_ENV

      - name: Update README
        run: |
          echo "Updating README with repository: $LATEST_REPO"
          if [ "$IS_PRIVATE" = "true" ]; then
            sed -i "s|\[.*\](https://github.com/SkyNetCloud/.*)|$LATEST_REPO|" README.md
          else
            sed -i "s|\[.*\](https://github.com/SkyNetCloud/.*)|[$LATEST_REPO]($LATEST_REPO_URL)|" README.md
          fi

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "SkyNetCloud"
          git config --global user.email "mcboxer1201@gmail.com"
          git remote set-url origin https://SkyNetCloud:${GITHUB_TOKEN}@github.com/SkyNetCloud/SkyNetCloud.git
          git add README.md
          git commit -m "Updated current project to $LATEST_REPO" || exit 0
          git push origin main
